frontend/src/bundles/common/components/button/styles.module.scss

correct blue color was also fixed

ss-5: Fix Buttons border-radius

---

frontend/src/assets/css/variables/color-variables.scss
frontend/src/bundles/common/components/user-settings-tabs/styles.module.scss

ss-123: Fix User Setting Tabs Colors

---

frontend/src/bundles/auth/components/sign-up-form/sign-up-form.tsx
frontend/src/bundles/auth/components/sign-up-form/styles.module.scss
frontend/src/bundles/auth/pages/styles.module.scss
frontend/src/bundles/common/components/input/styles.module.scss
frontend/src/bundles/common/helpers/get-text-to-path/get-text-to-path.ts
frontend/src/bundles/common/hooks/use-app-form/use-app-form.hook.ts

ss-108: [BUG] Several visual defects on the "Sign Up" page

---

frontend/src/bundles/common/components/header/styles.module.scss
frontend/src/bundles/landing/components/feedbacks-part/styles.module.scss
frontend/src/bundles/landing/components/first-step-part/styles.module.scss
frontend/src/bundles/landing/components/highlight-banner/styles.module.scss
frontend/src/bundles/landing/components/second-step-part/styles.module.scss
frontend/src/bundles/landing/components/store-button/styles.module.scss
frontend/src/bundles/landing/components/subscription-part/styles.module.scss
frontend/src/bundles/landing/components/third-step-part/styles.module.scss

ss-119: Responsive layout on landing page doesn't behave as expected

---

frontend/src/bundles/common/enums/app-route.enum.ts
frontend/src/bundles/common/pages/not-found/not-found.tsx
frontend/src/bundles/common/pages/not-found/styles.module.scss
frontend/src/index.tsx

ss-166: Add 404 error page

---

frontend/src/bundles/landing/components/subscription-part/styles.module.scss
frontend/src/bundles/landing/components/subscription-part/subscription-part.tsx

ss-183: Change Input And Button Styles On Landing Page

---

frontend/src/bundles/common/components/header/styles.module.scss
frontend/src/bundles/common/pages/base.tsx
frontend/src/bundles/landing/landing.tsx
frontend/src/bundles/landing/styles.module.scss

ss-156: Make the header on the Landing page static

---

frontend/src/bundles/common/components/bar-chart/bar-chart.tsx
frontend/src/bundles/common/components/bar-chart/config-bar.ts
frontend/src/bundles/common/components/components.ts
frontend/src/bundles/common/components/input/styles.module.scss
frontend/src/bundles/common/pages/base.tsx
frontend/src/bundles/common/pages/dashboard/dashboard.tsx
frontend/src/bundles/common/pages/dashboard/mocks.dashboard.ts
frontend/src/bundles/common/pages/dashboard/styles.module.scss

ss-178: Fix missing elements on dashboard page

---

frontend/src/bundles/auth/components/sign-in-form/styles.module.scss
frontend/src/bundles/auth/components/sign-up-form/styles.module.scss
frontend/src/bundles/common/components/input/input.tsx

ss-204: [BUG] The data in the password fields overlap the eye icons on the Log In/Sign Up pages

---

frontend/package.json
frontend/src/assets/css/variables/color-variables.scss
frontend/src/bundles/common/components/button/button.tsx
frontend/src/bundles/common/components/button/styles.module.scss
frontend/src/bundles/common/components/dropdown/dropdown.tsx
frontend/src/bundles/common/components/settings/styles.module.scss
frontend/src/bundles/common/components/settings/title.tsx
frontend/src/bundles/common/components/settings/user-profile.tsx
frontend/src/bundles/common/components/settings/user-profile/avatar-container.tsx
frontend/src/bundles/common/components/settings/user-profile/avatar.tsx
frontend/src/bundles/common/components/settings/user-profile/delete-avatar-button.tsx
frontend/src/bundles/common/components/settings/user-profile/mock-data.ts
frontend/src/bundles/common/components/settings/user-profile/settings-form.tsx
frontend/src/bundles/common/components/settings/user-profile/submit-button.tsx
frontend/src/bundles/common/components/settings/user-profile/upload-avatar-button.tsx
frontend/src/bundles/common/enums/button-variant.enum.ts
frontend/src/bundles/common/pages/base.tsx
package-lock.json
shared/src/bundles/users/types/user-change-settings-request.ts

https://www.loom.com/share/f3c26a33672a4011b31a8628cda5bfca

ss-70: + user profile page

---

frontend/src/bundles/common/components/input/styles.module.scss

ss-261: Fix hover state on inputs

---

frontend/src/bundles/common/components/modal-add-wallet/styles.module.scss

ss-269: Fix button color change

---

frontend/src/bundles/common/pages/wallet-details/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

ss-278: Wallet details page doesnt match design

---

frontend/src/bundles/common/components/input/styles.module.scss
frontend/src/bundles/common/pages/dashboard/dashboard.tsx
frontend/src/bundles/common/pages/dashboard/mocks.dashboard.ts
frontend/src/bundles/common/pages/dashboard/styles.module.scss

ss-268: Filters on the Dashboard page don't match the design

---

frontend/src/bundles/common/components/modal-add-wallet/styles.module.scss

additional changes to border-radius and font family

ss-269: Button font and radius update

---

frontend/src/bundles/common/components/input/styles.module.scss

ss-276: Input font size update

---

backend/src/bundles/currencies/currencies.ts
backend/src/bundles/currencies/currency.controller.ts
backend/src/bundles/currencies/currency.entity.ts
backend/src/bundles/currencies/currency.model.ts
backend/src/bundles/currencies/currency.repository.ts
backend/src/bundles/currencies/currency.service.ts
backend/src/bundles/currencies/enums/enums.ts
backend/src/bundles/currencies/types/types.ts
backend/src/common/database/enums/database-table-name.enum.ts
backend/src/common/server-application/server-application.ts
frontend/src/app/app.tsx
frontend/src/bundles/currencies/currencies-api.ts
frontend/src/bundles/currencies/currencies.ts
frontend/src/bundles/currencies/enums/enums.ts
frontend/src/bundles/currencies/store/actions.ts
frontend/src/bundles/currencies/store/index.ts
frontend/src/bundles/currencies/store/slice.ts
frontend/src/bundles/currencies/types/types.ts
frontend/src/framework/store/store.package.ts
shared/src/bundles/currencies/currencies.ts
shared/src/bundles/currencies/enums/currency-api-path.enum.ts
shared/src/bundles/currencies/enums/currency-validation-message.enum.ts
shared/src/bundles/currencies/enums/enums.ts
shared/src/bundles/currencies/types/currency-get-all-item-response-dto.type.ts
shared/src/bundles/currencies/types/currency-get-all-response-dto.type.ts
shared/src/bundles/currencies/types/types.ts
shared/src/enums/api-path.enum.ts
shared/src/enums/exception-message.enum.ts
shared/src/index.ts

ss-307: Add service for unloading currencies from the database

---

frontend/src/bundles/account-settings/account-settings.tsx
frontend/src/bundles/account-settings/components/settings/styles.module.scss
frontend/src/bundles/account-settings/styles.module.scss
frontend/src/bundles/common/components/header/header.tsx
frontend/src/bundles/common/components/tabs/styles.module.scss
frontend/src/bundles/common/components/user-settings-tabs/styles.module.scss

ss-267: [BUG] Responsive layout on User Settings page doesn't behave as expected

---

backend/src/common/server-application/server-application.ts
frontend/src/bundles/common/components/modal/styles.module.scss
frontend/src/bundles/common/components/transanction-table/components/styles.module.scss
frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/budgets/budget-details/components/budget-modal/budget-modal.tsx
frontend/src/bundles/common/pages/budgets/budget-details/components/budget-modal/styles.module.scss
frontend/src/bundles/common/pages/budgets/budget-details/styles.module.scss

ss-332: [BUG] Several visual defects on Budget details page

---

frontend/src/bundles/auth/components/sign-in-form/styles.module.scss
frontend/src/bundles/auth/components/sign-up-form/styles.module.scss

ss-284: Red border when error fix

---

backend/src/common/server-application/server-application.ts
frontend/src/bundles/common/components/range-slider/styles.module.scss
frontend/src/bundles/common/pages/dashboard/dashboard.tsx
frontend/src/bundles/common/pages/dashboard/styles.module.scss
shared/src/index.ts

ss-328: Fix styles on dashboard page

---

backend/src/bundles/transactions/transaction.entity.ts
backend/src/common/server-application/server-application.ts
shared/src/bundles/transactions/types/transaction-create-request-dto.type.ts
shared/src/bundles/transactions/types/transaction-get-all-item-response-dto.type.ts
shared/src/bundles/transactions/types/transaction-update-dto.type.ts
shared/src/bundles/transactions/validation-schemas/transaction-create-validation-schema.ts
shared/src/index.ts

**POST WITHOUT LABEL FILED**
**UPDATE WITHOUT LABEL FIELD**

ss-323: change label field to optional in transactions API

---

frontend/src/bundles/auth/components/auth-wrapper/styles.module.scss
frontend/src/bundles/auth/components/sign-up-form/styles.module.scss

ss-345: * [BAG]fix styles

---

frontend/src/bundles/common/pages/budgets/styles.module.scss

ss-336: Budget page title update

---

frontend/src/bundles/account-settings/account-settings.tsx
frontend/src/bundles/account-settings/components/settings/user-profile/settings-form.tsx
frontend/src/bundles/account-settings/styles.module.scss
frontend/src/bundles/common/components/user-settings-tabs/styles.module.scss

ss-321: user settings page redesign

---

frontend/src/bundles/auth/components/sign-up-form/sign-up-form.tsx
frontend/src/bundles/common/components/modal/modal.tsx

ss-379: fix sign up modal

---

frontend/src/bundles/common/components/bar-chart/config-bar.ts
frontend/src/bundles/common/pages/dashboard/dashboard.tsx
frontend/src/bundles/common/pages/dashboard/helpers/helpers.tsx
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

ss-365: Connect dashboard elements to backend

---

frontend/src/bundles/common/pages/dashboard/styles.module.scss

ss-368: Dashboard filters responsive layout fix

---

frontend/src/bundles/common/config/header-tabs.config.ts
frontend/src/bundles/common/pages/base.tsx
frontend/src/bundles/ui/components/header-part/header-part.tsx
frontend/src/bundles/ui/components/tabs-part/tabs-part.tsx

ss-393: Update tabs in the header on the wallet pages

---

frontend/src/bundles/common/components/menu/styles.module.scss

ss-389: Burger menu position fixed

---

backend/src/bundles/transactions/transaction.controller.ts
backend/src/bundles/transactions/transaction.entity.ts
backend/src/bundles/transactions/transaction.model.ts
backend/src/bundles/transactions/transaction.repository.ts
backend/src/bundles/transactions/transaction.service.ts
backend/src/bundles/wallets-transactions/types/types.ts
backend/src/bundles/wallets-transactions/wallets-transactions.entity.ts
backend/src/bundles/wallets-transactions/wallets-transactions.model.ts
backend/src/bundles/wallets-transactions/wallets-transactions.repository.ts
backend/src/bundles/wallets-transactions/wallets-transactions.service.ts
backend/src/bundles/wallets-transactions/wallets-transactions.ts
backend/src/bundles/wallets/wallets.controller.ts
backend/src/common/database/enums/database-table-name.enum.ts
backend/src/migrations/20230410083447_wallets_transactions.ts
backend/src/migrations/20230410090825_update_transactions_table.ts
shared/src/bundles/transactions/types/transaction-create-request-dto.type.ts
shared/src/bundles/transactions/validation-schemas/transaction-create-validation-schema.ts

ss-415: Connect wallet with transactions

---

backend/src/templates/sign-up-email-template.hbs
frontend/src/bundles/account-settings/account-settings.tsx
frontend/src/bundles/account-settings/components/settings/user-profile/settings-form.tsx

ss-435: update email template

---

backend/src/bundles/wallets/wallets.controller.ts
frontend/src/bundles/account-settings/account-settings.tsx
frontend/src/bundles/account-settings/components/settings/user-profile/settings-form.tsx

ss-453: Fix wallet transactions response

---

frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

ss-470: Remove Import button on Wallet details page

---

frontend/src/bundles/common/pages/categories-settings/categories-settings.tsx
frontend/src/bundles/common/pages/categories-settings/components/category-item/category-item.tsx
frontend/src/bundles/common/pages/categories-settings/components/category-item/styles.module.scss
frontend/src/bundles/common/pages/categories-settings/components/manage-categories/manage-categories.tsx

ss-463: - button Merge Categories and * button Delete in the modal

---

frontend/src/bundles/common/pages/wallet-settings/components/form-container/form-container.tsx
frontend/src/bundles/common/pages/wallet-settings/components/form-container/styles.module.scss

ss-458: + modal to delete wallet

---

frontend/src/bundles/common/components/calendar/calendar.tsx
frontend/src/bundles/common/components/calendar/components/one-day-calendar.tsx
frontend/src/bundles/common/components/transaction-modal/styles.module.scss
frontend/src/bundles/common/components/transaction-modal/transaction-modal-body.tsx
frontend/src/bundles/common/components/transanction-table/components/future-transactions/future-transactions.tsx
frontend/src/bundles/common/components/transanction-table/components/past-transactions/past-transactions.tsx
frontend/src/bundles/common/components/transanction-table/transaction-table.tsx

ss-481: [BUG] All transactions are created with today's date

---

frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/budgets/budget-details/styles.module.scss
frontend/src/bundles/common/pages/wallet-settings/components/form-container/form-container.tsx
frontend/src/bundles/common/pages/wallet-settings/components/form-container/styles.module.scss

ss-464: add modal to delete budget

---

frontend/src/bundles/account-settings/account-settings.tsx
frontend/src/bundles/common/components/modal-add-wallet/modal-add-wallet.tsx
frontend/src/bundles/common/components/modal-add-wallet/styles.module.scss

ss-391:  Create new wallet modal doesn't match the design on the dashboard page

---

frontend/src/bundles/common/components/doughnut-chart/doughnut-chart.tsx
frontend/src/bundles/common/components/loader/styles.module.scss
frontend/src/bundles/common/enums/fa-icons.enum.ts
frontend/src/bundles/common/icon-provider.ts
frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/budgets/budget-details/components/doughnut-chart-card/doughnut-chart-card.tsx
frontend/src/bundles/common/pages/budgets/budget-details/components/doughnut-chart-card/styles.module.scss
frontend/src/bundles/common/pages/budgets/budget-details/helpers/calculate-budget-details.helper.ts
frontend/src/bundles/common/pages/budgets/budget-details/helpers/gradient-doughnut.ts
frontend/src/bundles/common/pages/budgets/budget-details/styles.module.scss

ss-366: connect budget details page elements

---

frontend/src/bundles/common/components/transanction-table/components/transaction/transaction.tsx

ss-538: * [DAG]fix style

---

backend/src/bundles/categories/categories.ts
backend/src/bundles/categories/category.controller.ts
backend/src/bundles/categories/category.entity.ts
backend/src/bundles/categories/category.repository.ts
backend/src/bundles/categories/category.service.ts
backend/src/bundles/categories/types/types.ts
backend/src/bundles/user-categories/user-categories.entity.ts
backend/src/bundles/user-categories/user-categories.ts
backend/src/bundles/user-categories/user-category.controller.ts
backend/src/bundles/user-categories/user-category.model.ts
backend/src/bundles/user-categories/user-category.repository.ts
backend/src/bundles/user-categories/user-category.service.ts
backend/src/bundles/users/user.model.ts
backend/src/common/database/enums/database-table-name.enum.ts
backend/src/common/server-application/server-application.ts
shared/src/bundles/categories/categories.ts
shared/src/bundles/categories/enums/category-api-path.enum.ts
shared/src/bundles/categories/types/category-ids-request-dto.type.ts
shared/src/bundles/categories/types/types.ts
shared/src/enums/api-path.enum.ts
shared/src/index.ts

ss-494: + delete many categories route

---

frontend/src/bundles/common/components/header/header.tsx
frontend/src/bundles/common/components/transanction-table/components/future-transactions/future-transactions.tsx
frontend/src/bundles/common/components/transanction-table/components/styles.module.scss
frontend/src/bundles/common/components/transanction-table/transaction-table.tsx
frontend/src/bundles/common/enums/app-route.enum.ts
frontend/src/bundles/common/pages/future-transactions.tsx/future-transactions-page.tsx
frontend/src/bundles/common/pages/future-transactions.tsx/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx
frontend/src/index.tsx

ss-457: add future transactions page

---

frontend/src/bundles/account-settings/components/settings/user-profile/components/user-delete-modal/styles.module.scss
frontend/src/bundles/account-settings/components/settings/user-profile/components/user-delete-modal/user-delete-modal.tsx
frontend/src/bundles/common/components/modal/modal.tsx
frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/budgets/budget-details/styles.module.scss
frontend/src/bundles/common/pages/wallet-settings/components/form-container/form-container.tsx
frontend/src/bundles/common/pages/wallet-settings/components/form-container/styles.module.scss

ss-509: * refactor modal to confirm deletion

---

frontend/src/bundles/common/pages/budgets/budget-details/components/budget-modal/styles.module.scss

ss-498: [BUG] Buttons aren't aligned on the Edit Budget modal

---

frontend/src/bundles/common/pages/wallet-settings/components/form-container/form-container.tsx

ss-491: [BUG] User can update Wallet settings with empty fields

---

frontend/src/bundles/common/pages/budgets/budget-details/styles.module.scss

ss-547: Increase the size of Budget title on the Budget details page

---

frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-smartspend/pull/434

ss-554: * [BAG]fix style

---

frontend/src/bundles/common/pages/budgets/budget-details/components/budget-progress-bar/budget-progress-bar.tsx
frontend/src/bundles/common/pages/budgets/budget-details/components/budget-progress-bar/styles.module.scss

ss-516: Add percentage to Budget progress bar

---

frontend/src/bundles/account-settings/components/settings/styles.module.scss
frontend/src/bundles/account-settings/components/settings/user-profile.tsx
frontend/src/bundles/auth/components/sign-up-form/sign-up-form.tsx
frontend/src/bundles/common/components/header-user-button/header-user-button.tsx
frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/budgets/budget-details/styles.module.scss
frontend/src/bundles/common/pages/budgets/budgets.tsx
frontend/src/bundles/common/pages/budgets/styles.module.scss
frontend/src/bundles/common/pages/dashboard/dashboard.tsx
frontend/src/bundles/common/pages/dashboard/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

ss-533: Add loader components on pages

---

frontend/src/bundles/common/components/budget-card/budget-card.tsx

ss-495: - mock data

---

frontend/src/bundles/common/pages/budgets/budget-details/components/budget-modal/budget-modal.tsx
frontend/src/bundles/common/pages/budgets/budget-details/components/budget-modal/styles.module.scss

ss-541: Update "Create new Budget" modal

---

frontend/src/bundles/common/components/budget-card/budget-card.tsx
frontend/src/bundles/common/components/range-slider/styles.module.scss
frontend/src/bundles/common/helpers/get-max-min-transaction-amount/get-max-min-transaction-amount.helper.ts
frontend/src/bundles/common/pages/dashboard/dashboard.tsx
frontend/src/bundles/common/pages/dashboard/styles.module.scss
frontend/src/bundles/common/pages/future-transactions/future-transactions-page.tsx
frontend/src/bundles/common/pages/future-transactions/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

ss-531: Update Wallet Transactions page

---

frontend/src/bundles/landing/components/first-step-part/first-step-part.tsx

ss-571: rewrite text in step 1 on landing

---

frontend/src/bundles/common/pages/budgets/budget-details/components/multi-dropdown/multi-dropdown.tsx

ss-544: * [BAG] icons to the drop-down

---

frontend/src/bundles/common/config/header-tabs.config.ts
frontend/src/bundles/common/pages/budgets/budget-details/components/budget-modal/styles.module.scss

ss-572: [BUG] Responsive layout on "Create/Edit budget" modal window doesn't behave as expected

---

frontend/src/bundles/common/pages/wallet-settings/wallet-settings.tsx

ss-599: - remove tabs in wallet settings

---

frontend/src/bundles/common/components/budget-card/budget-card.tsx
frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/budgets/budget-details/helpers/calculate-budget-details.helper.ts
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

ss-605: The Total Wallet Balance is calculated incorrectly

---

frontend/src/assets/css/scaffolding.scss

ss-607: fixed styles in cards and in budgets

---

frontend/src/bundles/common/components/transaction-modal/styles.module.scss
frontend/src/bundles/common/components/transaction-modal/transaction-modal.tsx
frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/budgets/budget-details/styles.module.scss
frontend/src/bundles/common/pages/categories-settings/components/manage-categories/manage-categories.tsx
frontend/src/bundles/common/pages/categories-settings/components/manage-categories/styles.module.scss

ss-594: + modal to confirm transaction deletion and refactor modal to confirm categories deletion

---

frontend/src/bundles/account-settings/account-settings.tsx
frontend/src/bundles/account-settings/styles.module.scss
frontend/src/bundles/common/components/user-settings-tabs/components/user-settings-tab/user-settings-tab.tsx
frontend/src/bundles/common/components/user-settings-tabs/styles.module.scss
frontend/src/bundles/common/components/user-settings-tabs/user-settings-tabs.tsx

ss-517: Add footer menu to Account settings

---

frontend/src/bundles/common/components/transanction-table/components/styles.module.scss
frontend/src/bundles/common/components/transanction-table/components/transaction/transaction.tsx

ss-542: + note to transaction table

---

frontend/src/bundles/common/components/transaction-modal/transaction-modal.tsx
frontend/src/bundles/common/pages/categories-settings/components/category-item/category-item.tsx
frontend/src/bundles/common/pages/categories-settings/components/category-item/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

ss-615: * refactor modal to delete several transaction and refactor modal to delete one category

---

frontend/src/bundles/account-settings/styles.module.scss

ss-626: Account settings small screen z-index fix

---

frontend/src/bundles/common/components/budget-card/budget-card.tsx
frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx

ss-609: The Money left is calculated incorrectly on the Budget details page

---

frontend/src/bundles/account-settings/styles.module.scss
frontend/src/bundles/common/components/transanction-table/components/future-transactions/future-transactions.tsx
frontend/src/bundles/common/components/transanction-table/components/styles.module.scss
frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/categories-settings/components/category-item/category-item.tsx
frontend/src/bundles/common/pages/categories-settings/components/manage-categories/manage-categories.tsx
frontend/src/bundles/common/pages/dashboard/dashboard.tsx
frontend/src/bundles/common/pages/future-transactions/future-transactions-page.tsx
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

more than 1 transaction
1 transaction

ss-633: Change "operation" to "transactions" on the categories table

---

frontend/src/bundles/common/components/transanction-table/components/future-transactions/future-transactions.tsx

ss-637: Turn over the check mark in the dropdown tables of future transactions

---

frontend/src/bundles/account-settings/components/settings/user-profile/settings-form.tsx
frontend/src/bundles/common/components/transaction-modal/styles.module.scss
frontend/src/bundles/common/components/transanction-table/components/styles.module.scss
frontend/src/bundles/common/components/transanction-table/components/transaction/transaction.tsx
frontend/src/bundles/common/pages/dashboard/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

ss-652: fix styles in category dropdown and future transactions items

---

frontend/src/bundles/account-settings/components/settings/user-profile/settings-form.tsx
frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/dashboard/dashboard.tsx
frontend/src/bundles/users/store/actions.ts

ss-658: [BUG] Rename 3rd card on the Budget Details page

---

frontend/src/bundles/common/pages/budgets/budget-details/components/multi-dropdown/styles.module.scss
frontend/src/bundles/common/pages/future-transactions/future-transactions-page.tsx
frontend/src/bundles/common/pages/future-transactions/styles.module.scss

ss-681: fix categories dropdown on future transactions page and budget dropdown

---

frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
frontend/src/bundles/common/pages/future-transactions/future-transactions-page.tsx
frontend/src/bundles/common/pages/future-transactions/styles.module.scss
frontend/src/bundles/common/pages/wallet-details/wallet-details.tsx

ss-684: [UI BUG] Update modals to confirm several transactions deletion on the Budget details page

---

frontend/src/bundles/common/constants/constants.ts
frontend/src/bundles/common/constants/wallet-card-variants.constant.ts
frontend/src/bundles/common/pages/dashboard/dashboard.tsx

ss-674: Change card variants

---

frontend/src/bundles/common/pages/dashboard/helpers/helpers.tsx

ss-699: Fix doughnut charts on the Dashboard page

---

frontend/src/bundles/common/pages/dashboard/dashboard.tsx

ss-695: Fix make design if not transactions on Dashbord
